gcp_project = "crucial-strata-311604"
gcp_region  = "us-central1"
//gcp_auth_file = "tf-key.json"
gcp_zone = "us-central1-c"
//gcp_network = "myvpcnetwork"
gcp_instancename = "terraform-custom-network-stage"
gcp_machinetype  = "e2-micro"
gcp_auth_file    = "./SA_key.json"

bucket_name   = "mytftestbucket-stage"
storage_class = "REGIONAL"